module.exports = {
  SET_GLOBAL: 'SET_GLOBAL',
  SET_PROCESS_PARAM: 'SET_PROCESS_PARAM',
  DELETE_PROCESS_PARAM: 'DELETE_PROCESS_PARAM',
  SET_PROCESS_URL: 'SET_PROCESS_URL',
  SET_PROCESS_METHOD: 'SET_PROCESS_METHOD',
  SET_PROCESS_PARAM_JSON: 'SET_PROCESS_PARAM_JSON',
  ADD_PROCESS: 'ADD_PROCESS',
  SET_CURRENT_PROCESS: 'SET_CURRENT_PROCESS',
  ADD_ROW: 'ADD_ROW',
  DELETE_PROCESS: 'DELETE_PROCESS',
  SET_FORMAT_TYPE: 'SET_FORMAT_TYPE',
  SET_NAME: 'SET_NAME',
  SET_DEMO_DATA: 'SET_DEMO',
  SET_REQUEST_OPTIONS: 'SET_REQUEST_OPTIONS',
  SET_REQUEST_RESULT: 'SET_REQUEST_RESULT',
  RESET_REQUEST: 'RESET_REQUEST',
  SET_PROCESS_ASSERT: 'SET_PROCESS_ASSERT'
};
