module.exports = {
  SET_GLOBAL: 'SET_GLOBAL',
  SET_PROCESS_PARAM: 'SET_PROCESS_PARAM',
  DELETE_PROCESS_PARAM: 'DELETE_PROCESS_PARAM',
  SET_PROCESS_URL: 'SET_PROCESS_URL',
  SET_PROCESS_METHOD: 'SET_PROCESS_METHOD',
  SET_PROCESS_PARAM_JSON: 'SET_PROCESS_PARAM_JSON',
  ADD_PROCESS: 'ADD_PROCESS',
  SET_CURRENT_PROCESS: 'SET_CURRENT_PROCESS',
  ADD_ROW: 'ADD_ROW',
  DELETE_PROCESS: 'DELETE_PROCESS'
};
